spring:
  application:
    name: geo-service

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:file:./data/postcode_db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  security:
    user:
      name: admin
      password: secret

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
  api-docs:
    enabled: true